# Generated by Django 3.2.5 on 2021-07-11 01:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observatory',
            fields=[
                ('id', models.URLField(default=uuid.UUID('a0af5a13-12b7-4351-adbe-41d7805e4319'), editable=False, primary_key=True, serialize=False)),
                ('observatory_code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.URLField(default=uuid.UUID('893faf11-080d-410c-b3fa-5310fd02e91c'), editable=False, primary_key=True, serialize=False)),
                ('device_code', models.CharField(max_length=32, unique=True)),
                ('device_resolution', models.CharField(max_length=5)),
                ('observatories', models.ManyToManyField(to='asteroid.Observatory')),
            ],
        ),
        migrations.CreateModel(
            name='Asteriod',
            fields=[
                ('id', models.URLField(default=uuid.UUID('eccc6995-9c8b-432a-a138-2471aaa7c968'), editable=False, primary_key=True, serialize=False)),
                ('device_matrix', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('devices', models.ManyToManyField(to='asteroid.Device')),
            ],
        ),
    ]
