# Generated by Django 3.2.5 on 2021-07-11 23:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.URLField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observatory_code', models.CharField(max_length=32, unique=True)),
                ('device_code', models.CharField(max_length=32, unique=True)),
                ('device_resolution', models.CharField(max_length=5)),
                ('device_matrix', models.CharField(max_length=64, unique=True)),
                ('device_matrix_clear', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
