# Generated by Django 3.2.5 on 2021-07-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asteroid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='device_code',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='observatory_code',
            field=models.CharField(max_length=32),
        ),
    ]
