# Generated by Django 3.2.5 on 2021-07-11 01:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('asteroid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteriod',
            name='device_matrix',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='asteriod',
            name='id',
            field=models.URLField(default=uuid.UUID('fd7bd2ca-cc06-486a-b78b-49e2f33286ad'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.URLField(default=uuid.UUID('f0fdaa3b-aebf-4ed6-8952-625b242490be'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='id',
            field=models.URLField(default=uuid.UUID('ad71cba7-34a8-4179-b53c-d65401c1db6e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
